version: "3.9"

services:

#  postgres:
#    image: postgres:16-alpine
#    container_name: finance-postgres
#    env_file:
#      - .env
#    environment:
#      - "POSTGRES_DB: ${POSTGRES_DB}"
#      - "POSTGRES_USER: ${POSTGRES_USER}"
#      - "POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}"
#      - "POSTGRES_HOST_AUTH_METHOD: 'md5'"
#      - "POSTGRES_INITDB_ARGS='--encoding=UTF-8'"
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-api
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-dev}
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
